dataset: combined
ithor_scenes:
- FloorPlan1
- FloorPlan4
- FloorPlan21
- FloorPlan226
- FloorPlan209
- FloorPlan219
- FloorPlan320
- FloorPlan321
- FloorPlan327
- FloorPlan413
- FloorPlan415
- FloorPlan406
num_ithor: 12
num_robothor: 14
num_scenes: 26
robothor_scenes:
- FloorPlan_Test1_1
- FloorPlan_Test1_2
- FloorPlan_Test2_1
- FloorPlan_Test2_2
- FloorPlan_Test3_1
- FloorPlan_Test3_2
- FloorPlan_Test4_1
- FloorPlan_Test4_2
- FloorPlan_Test5_1
- FloorPlan_Test5_2
- FloorPlan_Test6_1
- FloorPlan_Test6_2
- FloorPlan_Test7_1
- FloorPlan_Test7_2
scenes:
- FloorPlan_Test7_1
- FloorPlan_Test3_1
- FloorPlan406
- FloorPlan_Test1_2
- FloorPlan209
- FloorPlan_Test2_1
- FloorPlan321
- FloorPlan226
- FloorPlan_Test4_2
- FloorPlan_Test7_2
- FloorPlan_Test1_1
- FloorPlan21
- FloorPlan_Test5_2
- FloorPlan327
- FloorPlan1
- FloorPlan219
- FloorPlan_Test2_2
- FloorPlan_Test6_1
- FloorPlan_Test5_1
- FloorPlan415
- FloorPlan_Test6_2
- FloorPlan_Test3_2
- FloorPlan_Test4_1
- FloorPlan4
- FloorPlan320
- FloorPlan413
split: test
