dataset: combined
ithor_scenes:
- FloorPlan8
- FloorPlan9
- FloorPlan24
- FloorPlan206
- FloorPlan225
- FloorPlan201
- FloorPlan307
- FloorPlan319
- FloorPlan312
- FloorPlan423
- FloorPlan421
- FloorPlan409
num_ithor: 12
num_robothor: 15
num_scenes: 27
robothor_scenes:
- FloorPlan_Val1_1
- FloorPlan_Val1_2
- FloorPlan_Val1_3
- FloorPlan_Val2_1
- FloorPlan_Val2_2
- FloorPlan_Val2_3
- FloorPlan_Val3_1
- FloorPlan_Val3_2
- FloorPlan_Val3_3
- FloorPlan_Val4_1
- FloorPlan_Val4_2
- FloorPlan_Val4_3
- FloorPlan_Val5_1
- FloorPlan_Val5_2
- FloorPlan_Val5_3
scenes:
- FloorPlan_Val5_3
- FloorPlan423
- FloorPlan421
- FloorPlan_Val5_2
- FloorPlan312
- FloorPlan206
- FloorPlan_Val5_1
- FloorPlan_Val4_1
- FloorPlan225
- FloorPlan409
- FloorPlan_Val3_2
- FloorPlan_Val2_2
- FloorPlan_Val4_2
- FloorPlan_Val4_3
- FloorPlan_Val1_3
- FloorPlan_Val1_1
- FloorPlan307
- FloorPlan_Val3_1
- FloorPlan_Val2_1
- FloorPlan_Val1_2
- FloorPlan201
- FloorPlan319
- FloorPlan24
- FloorPlan8
- FloorPlan_Val2_3
- FloorPlan_Val3_3
- FloorPlan9
split: val
