test:
- FloorPlan_Train5_1
- FloorPlan_Train2_2
- FloorPlan406
- FloorPlan_Train1_2
- FloorPlan209
- FloorPlan_Train1_3
- FloorPlan321
- FloorPlan226
- FloorPlan_Train3_2
- FloorPlan_Train5_2
- FloorPlan_Train1_1
- FloorPlan21
- FloorPlan_Train4_1
- FloorPlan327
- FloorPlan1
- FloorPlan219
- FloorPlan_Train2_1
- FloorPlan_Train4_2
- FloorPlan_Train3_3
- FloorPlan415
- FloorPlan_Train4_3
- FloorPlan_Train2_3
- FloorPlan_Train3_1
- FloorPlan4
- FloorPlan320
- FloorPlan413
train:
- FloorPlan205
- FloorPlan7
- FloorPlan229
- FloorPlan316
- FloorPlan19
- FloorPlan418
- FloorPlan407
- FloorPlan16
- FloorPlan6
- FloorPlan402
- FloorPlan426
- FloorPlan_Train10_4
- FloorPlan215
- FloorPlan_Train12_5
- FloorPlan_Train3_5
- FloorPlan_Train2_4
- FloorPlan404
- FloorPlan325
- FloorPlan_Train4_5
- FloorPlan_Train8_1
- FloorPlan_Train2_1
- FloorPlan_Train7_3
- FloorPlan306
- FloorPlan314
- FloorPlan_Train3_1
- FloorPlan405
- FloorPlan26
- FloorPlan323
- FloorPlan_Train9_3
- FloorPlan_Train7_2
- FloorPlan315
- FloorPlan_Train10_2
- FloorPlan216
- FloorPlan329
- FloorPlan207
- FloorPlan_Train7_4
- FloorPlan228
- FloorPlan430
- FloorPlan210
- FloorPlan_Train4_3
- FloorPlan313
- FloorPlan14
- FloorPlan_Train12_1
- FloorPlan227
- FloorPlan401
- FloorPlan417
- FloorPlan422
- FloorPlan301
- FloorPlan427
- FloorPlan27
- FloorPlan_Train9_4
- FloorPlan211
- FloorPlan318
- FloorPlan_Train11_5
- FloorPlan324
- FloorPlan_Train6_4
- FloorPlan410
- FloorPlan_Train11_1
- FloorPlan202
- FloorPlan15
- FloorPlan_Train1_1
- FloorPlan23
- FloorPlan_Train8_4
- FloorPlan208
- FloorPlan28
- FloorPlan330
- FloorPlan_Train11_2
- FloorPlan_Train2_3
- FloorPlan322
- FloorPlan425
- FloorPlan_Train2_5
- FloorPlan_Train1_5
- FloorPlan212
- FloorPlan309
- FloorPlan_Train9_1
- FloorPlan_Train5_3
- FloorPlan29
- FloorPlan303
- FloorPlan311
- FloorPlan_Train5_5
- FloorPlan_Train12_4
- FloorPlan_Train10_5
- FloorPlan12
- FloorPlan408
- FloorPlan424
- FloorPlan10
- FloorPlan429
- FloorPlan420
- FloorPlan13
- FloorPlan218
- FloorPlan_Train9_5
- FloorPlan214
- FloorPlan17
- FloorPlan_Train8_2
- FloorPlan305
- FloorPlan222
- FloorPlan414
- FloorPlan_Train6_3
- FloorPlan_Train12_3
- FloorPlan_Train1_4
- FloorPlan302
- FloorPlan_Train6_5
- FloorPlan_Train5_1
- FloorPlan223
- FloorPlan3
- FloorPlan224
- FloorPlan412
- FloorPlan_Train4_4
- FloorPlan416
- FloorPlan_Train3_2
- FloorPlan230
- FloorPlan419
- FloorPlan_Train4_1
- FloorPlan22
- FloorPlan_Train5_2
- FloorPlan5
- FloorPlan_Train8_5
- FloorPlan_Train8_3
- FloorPlan220
- FloorPlan_Train6_1
- FloorPlan_Train4_2
- FloorPlan_Train11_3
- FloorPlan_Train6_2
- FloorPlan20
- FloorPlan326
- FloorPlan18
- FloorPlan317
- FloorPlan403
- FloorPlan_Train10_1
- FloorPlan428
- FloorPlan308
- FloorPlan221
- FloorPlan11
- FloorPlan304
- FloorPlan_Train5_4
- FloorPlan_Train1_2
- FloorPlan_Train1_3
- FloorPlan2
- FloorPlan_Train3_3
- FloorPlan204
- FloorPlan203
- FloorPlan217
- FloorPlan30
- FloorPlan25
- FloorPlan_Train7_1
- FloorPlan_Train7_5
- FloorPlan213
- FloorPlan328
- FloorPlan411
- FloorPlan_Train2_2
- FloorPlan_Train12_2
- FloorPlan_Train3_4
- FloorPlan_Train11_4
- FloorPlan310
- FloorPlan_Train9_2
- FloorPlan_Train10_3
val:
- FloorPlan_Val3_5
- FloorPlan423
- FloorPlan421
- FloorPlan_Val3_4
- FloorPlan312
- FloorPlan206
- FloorPlan_Val3_3
- FloorPlan_Val2_5
- FloorPlan225
- FloorPlan409
- FloorPlan_Val2_3
- FloorPlan_Val1_5
- FloorPlan_Val3_1
- FloorPlan_Val3_2
- FloorPlan_Val1_3
- FloorPlan_Val1_1
- FloorPlan307
- FloorPlan_Val2_2
- FloorPlan_Val1_4
- FloorPlan_Val1_2
- FloorPlan201
- FloorPlan319
- FloorPlan24
- FloorPlan8
- FloorPlan_Val2_1
- FloorPlan_Val2_4
- FloorPlan9
