dataset: combined
ithor_scenes:
- FloorPlan1
- FloorPlan4
- FloorPlan21
- FloorPlan226
- FloorPlan209
- FloorPlan219
- FloorPlan320
- FloorPlan321
- FloorPlan327
- FloorPlan413
- FloorPlan415
- FloorPlan406
num_ithor: 12
num_robothor: 14
num_scenes: 26
robothor_scenes:
- FloorPlan_Train1_1
- FloorPlan_Train1_2
- FloorPlan_Train1_3
- FloorPlan_Train2_1
- FloorPlan_Train2_2
- FloorPlan_Train2_3
- FloorPlan_Train3_1
- FloorPlan_Train3_2
- FloorPlan_Train3_3
- FloorPlan_Train4_1
- FloorPlan_Train4_2
- FloorPlan_Train4_3
- FloorPlan_Train5_1
- FloorPlan_Train5_2
scenes:
- FloorPlan_Train5_1
- FloorPlan_Train2_2
- FloorPlan406
- FloorPlan_Train1_2
- FloorPlan209
- FloorPlan_Train1_3
- FloorPlan321
- FloorPlan226
- FloorPlan_Train3_2
- FloorPlan_Train5_2
- FloorPlan_Train1_1
- FloorPlan21
- FloorPlan_Train4_1
- FloorPlan327
- FloorPlan1
- FloorPlan219
- FloorPlan_Train2_1
- FloorPlan_Train4_2
- FloorPlan_Train3_3
- FloorPlan415
- FloorPlan_Train4_3
- FloorPlan_Train2_3
- FloorPlan_Train3_1
- FloorPlan4
- FloorPlan320
- FloorPlan413
split: test
