_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.5
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.5
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 64
buffer_size:
    value: 2048
clip_ratio:
    value: 0.2
context_size:
    value: 5
device:
    value: cuda
distance_coef:
    value: 0.1
encoding_size:
    value: 256
entropy_coef:
    value: 0.01
eval_episodes:
    value: 10
eval_freq:
    value: 100
freeze_vision_encoder:
    value: false
gamma:
    value: 0.99
goal_prob:
    value: 0.5
hidden_dim:
    value: 512
image_size:
    value:
        - 96
        - 96
lam:
    value: 0.95
log_freq:
    value: 10
max_episode_steps:
    value: 500
max_grad_norm:
    value: 0.5
mha_ff_dim_factor:
    value: 4
mha_num_attention_heads:
    value: 4
mha_num_attention_layers:
    value: 4
ppo_epochs:
    value: 10
pretrained_vision_encoder:
    value: null
rollout_steps:
    value: 2048
run_name:
    value: nomad_rl_experiment_1
save_dir:
    value: ./checkpoints/nomad_rl
save_freq:
    value: 50
scene_names:
    value:
        - FloorPlan1
success_distance:
    value: 1
total_timesteps:
    value: 1000000
use_wandb:
    value: true
value_coef:
    value: 0.5
wandb_project:
    value: nomad-rl-ai2thor
